# yaml-language-server: $schema=https://spec.openapis.org/oas/3.1/schema/2022-10-07
---
openapi: 3.1.0
info:
  title: Machines API
  version: 0.1.0
paths:
  /machines:
    get:
      responses:
        "200":
          description: A list of machines.
          content:
            application/json:
              schema:
                type: object
                properties:
                  machines:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        region:
                          type: string
              examples:
                list:
                  summary: List of machines
                  value:
                    machines:
                      - id: mercury
                        region: us-west-2
                      - id: venus
                        region: us-west-2
                      - id: mars
                        region: us-east-1
