---
openapi: 3.1.0
info:
  title: Machines API
  version: 0.1.0
paths:
  /machines:
    get:
      responses:
        "200":
          description: List of machines.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Machine"
              examples:
                success:
                  value:
                    - id: mercury
                      region: us-east-1
                    - id: venus
                      region: us-west-1
                    - id: mars
                      region: us-west-2
  /machines/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
    get:
      responses:
        "200":
          description: A single machine.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Machine"
              examples:
                success:
                  value:
                    id: mercury
                    region: us-east-1
components:
  schemas:
    Machine:
      type: object
      properties:
        id:
          type: string
        region:
          anyOf:
            - type: string
              enum: [us-east-1, us-west-1, us-west-2]
            - type: string
      required: [id, region]
